### ISSUE TITLE
[2pt] Create reservation functionality

### ISSUE THREAD

**Issue by PrangonGhose** [PrangonGhose/Earthbnb-backend#10]
To reserve an appointment, the user has to select a date and city (username and selected item are autofilled).
  - Use the design based on the ["Book a vespa test-ride"](https://www.behance.net/gallery/26425031/Vespa-Responsive-Redesign/modules/173005583) and add all necessary inputs.
  - The user can also access the "Reserve" page from the navigation panel. In that case only username is autofilled.

**Comment by Vgonma** [comment]
- Only the correct dates should be available(Not reserved dates, starting has to before ending, starting and ending have to be from the present onwards.)
- When the user enters the reservation form from within a house details, the house should be preselected.
